// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lodi_mcmc_cpp
Rcpp::List lodi_mcmc_cpp(Rcpp::NumericVector Y_vec, int seed, int niter, int nburn, int thin, int K, int L, Rcpp::Nullable<Rcpp::NumericMatrix> X, Rcpp::Nullable<Rcpp::NumericMatrix> r_fixed, Rcpp::Nullable<Rcpp::NumericMatrix> Lambda_fixed, Rcpp::Nullable<Rcpp::NumericVector> eta_fixed, Rcpp::Nullable<Rcpp::NumericVector> sigma2_t_fixed, Rcpp::Nullable<Rcpp::NumericVector> rho_fixed, Rcpp::Nullable<Rcpp::NumericVector> alpha_fixed, Rcpp::Nullable<Rcpp::NumericVector> phi_g_fixed, Rcpp::Nullable<Rcpp::NumericVector> V_fixed);
RcppExport SEXP _LODI_lodi_mcmc_cpp(SEXP Y_vecSEXP, SEXP seedSEXP, SEXP niterSEXP, SEXP nburnSEXP, SEXP thinSEXP, SEXP KSEXP, SEXP LSEXP, SEXP XSEXP, SEXP r_fixedSEXP, SEXP Lambda_fixedSEXP, SEXP eta_fixedSEXP, SEXP sigma2_t_fixedSEXP, SEXP rho_fixedSEXP, SEXP alpha_fixedSEXP, SEXP phi_g_fixedSEXP, SEXP V_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Y_vec(Y_vecSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type r_fixed(r_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Lambda_fixed(Lambda_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type eta_fixed(eta_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type sigma2_t_fixed(sigma2_t_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type rho_fixed(rho_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type alpha_fixed(alpha_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type phi_g_fixed(phi_g_fixedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type V_fixed(V_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(lodi_mcmc_cpp(Y_vec, seed, niter, nburn, thin, K, L, X, r_fixed, Lambda_fixed, eta_fixed, sigma2_t_fixed, rho_fixed, alpha_fixed, phi_g_fixed, V_fixed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LODI_lodi_mcmc_cpp", (DL_FUNC) &_LODI_lodi_mcmc_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_LODI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
