# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lodi_mcmc_cpp <- function(Y_vec, seed, niter, nburn, thin, K, L, X = NULL, r_fixed = NULL, Lambda_fixed = NULL, eta_fixed = NULL, sigma2_t_fixed = NULL, rho_fixed = NULL, alpha_fixed = NULL, phi_g_fixed = NULL, V_fixed = NULL) {
    .Call(`_LODI_lodi_mcmc_cpp`, Y_vec, seed, niter, nburn, thin, K, L, X, r_fixed, Lambda_fixed, eta_fixed, sigma2_t_fixed, rho_fixed, alpha_fixed, phi_g_fixed, V_fixed)
}

